// Auto-derived reference & default seed data for the UDC Debit Note System.
// Extracted from the original single-file prototype (index.html) and normalized.
// NOTE: default user passwords here are placeholders; all accounts are forced to
//       change password on first login (must_change_password = 1).

const SEED = {
  coops: [
    { n: "Rawda", p: "P9", m: 6, b: 4 },
    { n: "Sabah Al-Ahmad", p: "P452", m: 5, b: 21 },
    { n: "Jaber Al-Ahmad", p: "P498", m: 4, b: 19 },
    { n: "Saad Al-Abdullah", p: "P53", m: 4, b: 14 },
    { n: "Sabah Salem", p: "P32", m: 4, b: 15 },
    { n: "Al Addan & Al-Qusour", p: "P30", m: 3, b: 21 },
    { n: "Al Andalus", p: "P43", m: 3, b: 4 },
    { n: "Al Defaa", p: "P40", m: 3, b: 0 },
    { n: "Al Naeem", p: "P515", m: 3, b: 0 },
    { n: "Mubarak Al-Kabeer & Al-Qurain", p: "P247", m: 3, b: 24 },
    { n: "Abdullah Al-Mobarek", p: "P183", m: 2, b: 5 },
    { n: "Ali Sabah Al-Salem", p: "P112", m: 2, b: 14 },
    { n: "Ardeiya", p: "P42", m: 2, b: 8 },
    { n: "Bayan", p: "P4", m: 2, b: 11 },
    { n: "Jabriya", p: "P5", m: 2, b: 4 },
    { n: "Jahra", p: "P52", m: 2, b: 15 },
    { n: "Mishref", p: "P33", m: 2, b: 9 },
    { n: "Naseem", p: "P69", m: 2, b: 15 },
    { n: "Rumaithiya", p: "P2", m: 2, b: 12 },
    { n: "Sulaibikhat", p: "P44", m: 2, b: 8 },
    { n: "Abu Fteerah", p: "P511", m: 1, b: 0 },
    { n: "Abu Halifa", p: "P213", m: 1, b: 0 },
    { n: "Adiliya", p: "P18", m: 1, b: 3 },
    { n: "Al Ahamdi", p: "P108", m: 1, b: 3 },
    { n: "Al Qairawan", p: "P325", m: 1, b: 3 },
    { n: "Al Rabiya", p: "P383", m: 1, b: 4 },
    { n: "Al Salam", p: "P200", m: 1, b: 4 },
    { n: "Al Shuhdaa", p: "P55", m: 1, b: 1 },
    { n: "Al Zahra", p: "P54", m: 1, b: 0 },
    { n: "Al- Siddeeq Coop -", p: "P626", m: 1, b: 0 },
    { n: "Al-Wafra", p: "P608", m: 1, b: 0 },
    { n: "Daher", p: "P29", m: 1, b: 6 },
    { n: "Daiya", p: "P13", m: 1, b: 2 },
    { n: "Eqailah Co Op Society", p: "P545", m: 1, b: 0 },
    { n: "Eshbelia Co-Op", p: "P377", m: 1, b: 4 },
    { n: "Fahad Al-Ahmad", p: "P503", m: 1, b: 5 },
    { n: "Fahaheel", p: "P23", m: 1, b: 6 },
    { n: "Faiha", p: "P16", m: 1, b: 4 },
    { n: "Farwaniya", p: "P45", m: 1, b: 5 },
    { n: "Ferdous", p: "P48", m: 1, b: 10 },
    { n: "Fintas", p: "P24", m: 1, b: 3 },
    { n: "Hadiya", p: "P26", m: 1, b: 6 },
    { n: "Hawally (?)", p: "", m: 1, b: 0 },
    { n: "Heteen", p: "P196", m: 1, b: 1 },
    { n: "Jaber Ali", p: "P25", m: 1, b: 9 },
    { n: "Keifan", p: "P15", m: 1, b: 5 },
    { n: "Khaitan", p: "P46", m: 1, b: 0 },
    { n: "Khaldiya", p: "P14", m: 1, b: 4 },
    { n: "Manqaf Co Op Society", p: "P475", m: 1, b: 0 },
    { n: "National Guard", p: "P37", m: 1, b: 0 },
    { n: "Nugra (?)", p: "", m: 1, b: 0 },
    { n: "Omariya", p: "P47", m: 1, b: 5 },
    { n: "P655-North West Sulaibkhat Co Op.", p: "p655", m: 1, b: 0 },
    { n: "P702-Al-Massayel", p: "p702", m: 1, b: 0 },
    { n: "Qadisiya", p: "P11", m: 1, b: 2 },
    { n: "Qurtuba", p: "P8", m: 1, b: 1 },
    { n: "Rihab", p: "P34", m: 1, b: 5 },
    { n: "Riqqa", p: "P28", m: 1, b: 7 },
    { n: "Sabah Naser", p: "P49", m: 1, b: 8 },
    { n: "Sabahiya", p: "P27", m: 1, b: 11 },
    { n: "Salmiya", p: "P1", m: 1, b: 10 },
    { n: "Salwa", p: "P31", m: 1, b: 6 },
    { n: "Shaab", p: "P12", m: 1, b: 3 },
    { n: "Shamiya", p: "P22", m: 1, b: 5 },
    { n: "Shorta", p: "P38", m: 1, b: 0 },
    { n: "Surra", p: "P6", m: 1, b: 3 },
    { n: "West Abdullah Mubarak", p: "P723", m: 1, b: 16 },
    { n: "Yarmouk", p: "P7", m: 1, b: 3 },
  ],
  brands: [
    "LAYS",
    "Frito-Lay",
    "Tasali",
    "Doritos",
    "Cheetos",
    "Sunbites",
    "Lavina",
    "Mac'n Cheese",
    "Gatorade",
    "Bare",
    "VP Quinoa",
  ],
  principals: ["SSFL", "IEC", "MGF", "CLT", "ORT"],
  channels: ["الجمعيات", "الأسواق", "البقالات", "الأونلاين"],
  letterTypes: [
    {
      k: "listing",
      ar: "اعتماد أصناف (Listing)",
      mode: "items",
      en: "Listing (item approval)",
    },
    { k: "stand", ar: "ستاند (Stand)", mode: "value", en: "Stand" },
    { k: "pallet", ar: "طبالي (Pallet)", mode: "value", en: "Pallet" },
    {
      k: "priceoff",
      ar: "برايس أوف (Price Off)",
      mode: "value",
      en: "Price Off",
    },
    { k: "cda_pct", ar: "CDA نسبة %", mode: "pct", en: "CDA (%)" },
    { k: "cda_fix", ar: "CDA ثابت (Fixed)", mode: "value", en: "CDA (Fixed)" },
    { k: "changeprice", ar: "تحديث بيانات / تغيير سعر", mode: "pricetable", en: "Price Update" },
  ],
  supervisors: [
    "Mahmoud Abu Zaid",
    "Ahmed Maher",
    "Mahmoud Refaat",
    "Ahmed Fawzy",
    "Khaled Ahmed",
    "Tamer Ghidan",
    "Ahmed Zahran",
    "Mahmoud Ramadan",
    "Mohamed Elsaid",
    "Alaa Taha Said",
    "Ahmed Abdelrahim",
    "Moenes Mahmoud",
    "Omar Sabri Mohammed",
    "Ahmed Abd El Raim",
    "Ahmed Kamal",
  ],
  channelsEn: {
    الجمعيات: "Co-ops",
    الأسواق: "Markets",
    البقالات: "Groceries",
    الأونلاين: "Online",
  },
};

const DEFAULT_DIST = [
  {
    sup: "Khaled Ahmed",
    sales: "Tarek",
    coop: "Rumaithiya",
    outlet: "Alrumithiya Co-Op Main",
    wob: 918,
  },
  {
    sup: "Ahmed Abdelrahim",
    sales: "Maher",
    coop: "Bayan",
    outlet: "Bayan Co-Op Main",
    wob: 371,
  },
  {
    sup: "Ahmed Abdelrahim",
    sales: "Sabri",
    coop: "Jabriya",
    outlet: "Jabriya Co-Op Main",
    wob: 149,
  },
  {
    sup: "Ahmed Abdelrahim",
    sales: "Maher",
    coop: "Surra",
    outlet: "Surra Co-Op Main",
    wob: 316,
  },
  {
    sup: "Ahmed Maher",
    sales: "Omar",
    coop: "Yarmouk",
    outlet: "Yarmouk Co-Op Main",
    wob: 65,
  },
  {
    sup: "Ahmed Abdelrahim",
    sales: "Sabri",
    coop: "Qurtuba",
    outlet: "Qurtoba Co-Op Main",
    wob: 490,
  },
  {
    sup: "Alaa Taha Said",
    sales: "Karim",
    coop: "Rawda",
    outlet: "Rawda Co-Op Main",
    wob: 971,
  },
  {
    sup: "Alaa Taha Said",
    sales: "Anas",
    coop: "Rawda",
    outlet: "Hawlly Co-Op",
    wob: 645,
  },
  {
    sup: "Mohamed Elsaid",
    sales: "Wael",
    coop: "Nugra Co-Op",
    outlet: "Nugra Co-Op",
    wob: 299,
  },
  {
    sup: "Ahmed Maher",
    sales: "Yousef",
    coop: "Qadisiya",
    outlet: "Qadisiya Co-Op Main",
    wob: 1082,
  },
  {
    sup: "Ahmed Maher",
    sales: "Omar",
    coop: "Shaab",
    outlet: "Shaab Co-Op Main",
    wob: 1138,
  },
  {
    sup: "Ahmed Maher",
    sales: "Yousef",
    coop: "Daiya",
    outlet: "Daiya Co-Op Main",
    wob: 718,
  },
  {
    sup: "Ahmed Maher",
    sales: "Omar",
    coop: "Khaldiya",
    outlet: "Khaldiya Co-Op Main",
    wob: 373,
  },
  {
    sup: "Ahmed Maher",
    sales: "Yousef",
    coop: "Keifan",
    outlet: "Kifan Co-Op Main",
    wob: 318,
  },
  {
    sup: "Ahmed Maher",
    sales: "Omar",
    coop: "Faiha",
    outlet: "Faiha Co-Op Main",
    wob: 629,
  },
  {
    sup: "Ahmed Maher",
    sales: "Yousef",
    coop: "Adiliya",
    outlet: "Adiliya Co-Op Main",
    wob: 594,
  },
  {
    sup: "Ahmed Maher",
    sales: "Omar",
    coop: "Shamiya",
    outlet: "Shamiya Co-Op Main",
    wob: 951,
  },
  {
    sup: "Omar Sabri Mohammed",
    sales: "Ihab",
    coop: "Fahaheel",
    outlet: "Fahaheel Co-Op  1",
    wob: 1338,
  },
  {
    sup: "Ahmed Zahran",
    sales: "Ziad",
    coop: "Fintas",
    outlet: "Fintas Co-Op Main",
    wob: 489,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Kareem",
    coop: "Jaber Ali",
    outlet: "Jaber Ali Co-Op Main",
    wob: 1262,
  },
  {
    sup: "Ahmed Zahran",
    sales: "Amir",
    coop: "Hadiya",
    outlet: "Hadiya Co-Op Main",
    wob: 800,
  },
  {
    sup: "Omar Sabri Mohammed",
    sales: "Sameh",
    coop: "Sabahiya",
    outlet: "Sabahiya Co-Op Main",
    wob: 1358,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Sami",
    coop: "Riqqa",
    outlet: "Riqqa Co-Op Main",
    wob: 806,
  },
  {
    sup: "Ahmed Zahran",
    sales: "Ziad",
    coop: "Daher",
    outlet: "Daher Co-Op Main",
    wob: 1135,
  },
  {
    sup: "Ahmed Zahran",
    sales: "Amir",
    coop: "Al Addan & Al-Qusour",
    outlet: "Al Addan & Al Qusour Smkt 1",
    wob: 445,
  },
  {
    sup: "Ahmed Abdelrahim",
    sales: "Maher",
    coop: "Al Addan & Al-Qusour",
    outlet: "Al Addan & Al Qusour Smkt.2",
    wob: 1230,
  },
  {
    sup: "Ahmed Abdelrahim",
    sales: "Sabri",
    coop: "Salwa",
    outlet: "Salwa Co-Op Main",
    wob: 2621,
  },
  {
    sup: "Alaa Taha Said",
    sales: "Karim",
    coop: "Sabah Salem",
    outlet: "Sabah Salem Co-Op Main 1",
    wob: 733,
  },
  {
    sup: "Ahmed Abd El Raim",
    sales: "Waleed",
    coop: "Sabah Salem",
    outlet: "Sabah Salem Co-Op 2",
    wob: 249,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Rami",
    coop: "Mishref",
    outlet: "Mishref Co-Op Main",
    wob: 3572,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Kareem",
    coop: "Rihab",
    outlet: "Alrehab Coop",
    wob: 578,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Nader",
    coop: "National Guard",
    outlet: "National Guard Co-Op Main",
    wob: 1729,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Fadi",
    coop: "Al Defaa",
    outlet: "Al Defaa Co-Op Main",
    wob: 3379,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Nader",
    coop: "Al Defaa",
    outlet: "Al Defaa - W.S",
    wob: 4155,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Sami",
    coop: "Ardeiya",
    outlet: "Ardeiya New Co-Op Main",
    wob: 140,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Kareem",
    coop: "Ardeiya",
    outlet: "Ardeiya Old  Co-Op Main",
    wob: 65,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Fadi",
    coop: "Al Andalus",
    outlet: "Alandalus Co-Op Main",
    wob: 568,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Nader",
    coop: "Sulibikhat",
    outlet: "Sulibikhat Co-Op Main",
    wob: 847,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Fadi",
    coop: "Sulibikhat",
    outlet: "Sulaibikhat Co-Op Doha Market",
    wob: 452,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Sami",
    coop: "Farwaniya",
    outlet: "Farwaniya Co-Op Main",
    wob: 127,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Kareem",
    coop: "Khaitan",
    outlet: "Khitan Co-Op Main",
    wob: 123,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Tarek",
    coop: "Omariya",
    outlet: "Omariya Co-Op Main",
    wob: 620,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Rami",
    coop: "Al Rabiya",
    outlet: "Rabiya Co-Op - Smkt",
    wob: 408,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Nader",
    coop: "Ferdous",
    outlet: "Ferdous Co-Op Main",
    wob: 355,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Bilal",
    coop: "Jahra",
    outlet: "Jahra Co-Op Main",
    wob: 123,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Hadi",
    coop: "Jahra",
    outlet: "Waha Co-Op",
    wob: 240,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Bilal",
    coop: "Naseem",
    outlet: "Oyoun Co-Op",
    wob: 541,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Hadi",
    coop: "Al Naeem",
    outlet: "Al Naeem Co-Op Taimaa Market",
    wob: 656,
  },
  {
    sup: "Ahmed Abdelrahim",
    sales: "Maher",
    coop: "Salmiya",
    outlet: "Salmiya Co-Op Main",
    wob: 49,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Bilal",
    coop: "Al Naeem",
    outlet: "Alnaeem (Naeem Market)",
    wob: 186,
  },
  {
    sup: "Ahmed Zahran",
    sales: "Ziad",
    coop: "Mubarak Al-Kabeer & Al-Qurain",
    outlet: "Mubarak Al Kabeer & Al Qurain Smkt3",
    wob: 1195,
  },
  {
    sup: "Alaa Taha Said",
    sales: "Anas",
    coop: "Sabah Salem",
    outlet: "Sabah Al Salem Co-Op 3",
    wob: 673,
  },
  {
    sup: "Mahmoud Ramadan",
    sales: "Jad",
    coop: "Rawda",
    outlet: "Rawda Co-Op No.2 New",
    wob: 324,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Hadi",
    coop: "Naseem",
    outlet: "Al Naseem Co-Op Main",
    wob: 150,
  },
  {
    sup: "Ahmed Abdelrahim",
    sales: "Sabri",
    coop: "Bayan",
    outlet: "Bayan Co-Op Main New",
    wob: 790,
  },
  {
    sup: "Alaa Taha Said",
    sales: "Karim",
    coop: "Rawda",
    outlet: "Rawda & Hawally S.M 3",
    wob: 206,
  },
  {
    sup: "Omar Sabri Mohammed",
    sales: "Ihab",
    coop: "Ali Sabah Al-Salem",
    outlet: "Ali Sabah Al Salem",
    wob: 2039,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Tarek",
    coop: "Shorta",
    outlet: "Central Market For Employees At M.O.I",
    wob: 4914,
  },
  {
    sup: "Ahmed Abd El Raim",
    sales: "Hani",
    coop: "Rawda",
    outlet: "Al Rawda Coop -Hawalli Supermarket 4",
    wob: 634,
  },
  {
    sup: "Alaa Taha Said",
    sales: "Anas",
    coop: "Rawda",
    outlet: "Al Rawda Coop",
    wob: 227,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Rami",
    coop: "Al Zahra",
    outlet: "Al Zahra Coop",
    wob: 3049,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Tarek",
    coop: "Heteen",
    outlet: "Heteen Coop Smkt.",
    wob: 445,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Rami",
    coop: "Al Salam",
    outlet: "Al Salam Coop",
    wob: 1036,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Tarek",
    coop: "Al Shuhdaa",
    outlet: "Al Shuhdaa Coop",
    wob: 682,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Sami",
    coop: "Abdullah Al-Mobarek",
    outlet: "Abdullah  Mubarak Super Market",
    wob: 610,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Bilal",
    coop: "Jabriya",
    outlet: "Jabriya Co-Op New Supermarket",
    wob: 742,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Hadi",
    coop: "Saad Al-Abdullah",
    outlet: "Saad Al Abdullah Coop Main 1",
    wob: 1042,
  },
  {
    sup: "Ahmed Zahran",
    sales: "Amir",
    coop: "Abu Halifa",
    outlet: "Abu Halifa Coop Main",
    wob: 759,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Bilal",
    coop: "Al Qairawan",
    outlet: "Al Qairawan Co-Op Main",
    wob: 1484,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Fadi",
    coop: "Al Defaa",
    outlet: "Subhan Market",
    wob: 656,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Nader",
    coop: "Al Andalus",
    outlet: "Al Andalus Co-Op Alnahda Smkt.",
    wob: 126,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Kareem",
    coop: "Fahad Al-Ahmad",
    outlet: "Fahad Al Ahmed Co-Op Main",
    wob: 668,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Sami",
    coop: "Sabah Naser",
    outlet: "Sabah Al Naser New Market",
    wob: 406,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Fadi",
    coop: "Al Andalus",
    outlet: "Al Andalus New Market",
    wob: 2887,
  },
  {
    sup: "Mahmoud Abu Zaid",
    sales: "Ali",
    coop: "Abdullah Al-Mobarek",
    outlet: "Abdullah Mubarak Market 2",
    wob: 112,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Hadi",
    coop: "Jaber Al-Ahmad",
    outlet: "Jaber Al Ahmed Co Op Main .1",
    wob: 16,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Bilal",
    coop: "Al Naeem",
    outlet: "Al Naeem Co-Op Al Qasar Main",
    wob: 345,
  },
  {
    sup: "Alaa Taha Said",
    sales: "Karim",
    coop: "Sabah Salem",
    outlet: "Sabah Al Salem Co-Op Br Market 4",
    wob: 128,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Hadi",
    coop: "Saad Al-Abdullah",
    outlet: "Saad Al Abdullah Co-Op Main 2",
    wob: 142,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Rami",
    coop: "Mubarak Al-Kabeer & Al-Qurain",
    outlet: "Mubarak Al Kabeer & Al Qurain Market 5",
    wob: 682,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Bilal",
    coop: "Saad Al-Abdullah",
    outlet: "Saad Abdullah Main Co-Op Main 3",
    wob: 99,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Hadi",
    coop: "Saad Al-Abdullah",
    outlet: "Saad Al Abdullah Co-Op Main 4",
    wob: 548,
  },
  {
    sup: "Mahmoud Ramadan",
    sales: "Nabil",
    coop: "Al Addan & Al-Qusour",
    outlet: "Al Addan & Al Qusour Smkt 3",
    wob: 409,
  },
  {
    sup: "Ahmed Zahran",
    sales: "Ziad",
    coop: "Mubarak Al-Kabeer & Al-Qurain",
    outlet: "Mubarak Al Kabeer & Qurain Smkt 4",
    wob: 1824,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Tarek",
    coop: "Mishref",
    outlet: "Mubarak Al Abdullah Smkt",
    wob: 438,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Kareem",
    coop: "Eshbelia Co-Op",
    outlet: "Eshbelia Co-Op Main",
    wob: 892,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Sami",
    coop: "Sabah Al-Ahmad",
    outlet: "Sabah Al-Ahmad Co Op Main 1",
    wob: 2635,
  },
  {
    sup: "Omar Sabri Mohammed",
    sales: "Sameh",
    coop: "Manqaf Co Op Society",
    outlet: "Manqaf Co Op Main",
    wob: 672,
  },
  {
    sup: "Omar Sabri Mohammed",
    sales: "Ihab",
    coop: "Ali Sabah Al-Salem",
    outlet: "Ali Sabah Al-Salem  Smkt. 2",
    wob: 707,
  },
  {
    sup: "Omar Sabri Mohammed",
    sales: "Sameh",
    coop: "Al Ahamdi",
    outlet: "Ahmadi Co Op - New Smkt",
    wob: 656,
  },
  {
    sup: "Mahmoud Abu Zaid",
    sales: "Hassan",
    coop: "Jaber Al-Ahmad",
    outlet: "Jaber Al Ahmed Souk Area 5",
    wob: 216,
  },
  {
    sup: "Ahmed Zahran",
    sales: "Amir",
    coop: "Abu Fteerah",
    outlet: "Abu Ftertah Co Op Main",
    wob: 968,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Kareem",
    coop: "Jaber Al-Ahmad",
    outlet: "Jaber Al-Ahmad Block 7 Main",
    wob: 123,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Nader",
    coop: "Hawally Co Op - Smkt 7",
    outlet: "Hawally Co Op - Smkt 7",
    wob: 314,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Sami",
    coop: "Sabah Al-Ahmad",
    outlet: "Sabah Al_Ahmad Coop Main B",
    wob: 1840,
  },
  {
    sup: "Omar Sabri Mohammed",
    sales: "Ihab",
    coop: "Al-Wafra",
    outlet: "Al-Wafra  Co-Op",
    wob: 719,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Rami",
    coop: "Rumaithiya",
    outlet: "Rumaithaya Co-Op Main Al Dahiya 11",
    wob: 1428,
  },
  {
    sup: "Ahmed Zahran",
    sales: "Ziad",
    coop: "P702-Al-Massayel",
    outlet: "Al-Massayel Co-Op",
    wob: 472,
  },
  {
    sup: "Ahmed Zahran",
    sales: "Amir",
    coop: "Eqailah Co Op Society",
    outlet: "Eqaila Co-Op Main",
    wob: 185,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Kareem",
    coop: "Sabah Al-Ahmad",
    outlet: "Sabah Al-Ahmad Main C",
    wob: 1309,
  },
  {
    sup: "Khaled Ahmed",
    sales: "Tarek",
    coop: "Al- Siddeeq Coop -",
    outlet: "Al- Siddeeq Coop",
    wob: 1039,
  },
  {
    sup: "Tamer Ghidan",
    sales: "Bilal",
    coop: "Jaber Al-Ahmad",
    outlet: "Jaber Al Ahmed Main2",
    wob: 820,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Sami",
    coop: "Sabah Al-Ahmad",
    outlet: "Sabah Alahmad Coop - Main -D",
    wob: 1319,
  },
  {
    sup: "Ahmed Fawzy",
    sales: "Fadi",
    coop: "P655-North West Sulaibkhat Co Op.",
    outlet: "North West Sulaibkhat Co Op.",
    wob: 1068,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Kareem",
    coop: "Sabah Al-Ahmad",
    outlet: "Sabah Al-Ahmad Co Op Main E",
    wob: 922,
  },
  {
    sup: "Mahmoud Refaat",
    sales: "Sami",
    coop: "West Abdullah Mubarak",
    outlet: "West Abdulla  Mubarak Main 1",
    wob: 2249,
  },
];

const DEFAULT_USERS = [
  { u: "admin", p: "admin", name: "System Admin", role: "admin" },
  {
    u: "marketing",
    p: "1234",
    name: "مدير التسويق — Marketing",
    role: "marketing",
  },
  { u: "division", p: "1234", name: "مدير القسم — Division", role: "division" },
  { u: "doc", p: "1234", name: "التوثيق — Documentation", role: "doc" },
  {
    u: "mahmoud.zaid",
    p: "1234",
    name: "Mahmoud Abu Zaid",
    role: "supervisor",
  },
  { u: "ahmed.maher", p: "1234", name: "Ahmed Maher", role: "supervisor" },
  {
    u: "mahmoud.refaat",
    p: "1234",
    name: "Mahmoud Refaat",
    role: "supervisor",
  },
  { u: "ahmed.fawzy", p: "1234", name: "Ahmed Fawzy", role: "supervisor" },
  { u: "khaled.ahmed", p: "1234", name: "Khaled Ahmed", role: "supervisor" },
  { u: "tamer.ghidan", p: "1234", name: "Tamer Ghidan", role: "supervisor" },
  { u: "ahmed.zahran", p: "1234", name: "Ahmed Zahran", role: "supervisor" },
  {
    u: "mahmoud.ramadan",
    p: "1234",
    name: "Mahmoud Ramadan",
    role: "supervisor",
  },
  {
    u: "mohamed.elsaid",
    p: "1234",
    name: "Mohamed Elsaid",
    role: "supervisor",
  },
  { u: "alaa.said", p: "1234", name: "Alaa Taha Said", role: "supervisor" },
  {
    u: "ahmed.abdelrahim",
    p: "1234",
    name: "Ahmed Abdelrahim",
    role: "supervisor",
  },
  {
    u: "moenes.mahmoud",
    p: "1234",
    name: "Moenes Mahmoud",
    role: "supervisor",
  },
  {
    u: "omar.mohammed",
    p: "1234",
    name: "Omar Sabri Mohammed",
    role: "supervisor",
  },
  { u: "ahmed.raim", p: "1234", name: "Ahmed Abd El Raim", role: "supervisor" },
  { u: "ahmed.kamal", p: "1234", name: "Ahmed Kamal", role: "supervisor" },
  { u: "salesman.one", p: "1234", name: "Salesman One", role: "salesman" },
  { u: "salesman.two", p: "1234", name: "Salesman Two", role: "salesman" },
  { u: "ali", p: "1234", name: "Ali", role: "salesman" },
  { u: "amir", p: "1234", name: "Amir", role: "salesman" },
  { u: "anas", p: "1234", name: "Anas", role: "salesman" },
  { u: "bilal", p: "1234", name: "Bilal", role: "salesman" },
  { u: "fadi", p: "1234", name: "Fadi", role: "salesman" },
  { u: "hadi", p: "1234", name: "Hadi", role: "salesman" },
  { u: "hani", p: "1234", name: "Hani", role: "salesman" },
  { u: "hassan", p: "1234", name: "Hassan", role: "salesman" },
  { u: "ihab", p: "1234", name: "Ihab", role: "salesman" },
  { u: "jad", p: "1234", name: "Jad", role: "salesman" },
  { u: "kareem", p: "1234", name: "Kareem", role: "salesman" },
  { u: "karim", p: "1234", name: "Karim", role: "salesman" },
  { u: "maher", p: "1234", name: "Maher", role: "salesman" },
  { u: "nabil", p: "1234", name: "Nabil", role: "salesman" },
  { u: "nader", p: "1234", name: "Nader", role: "salesman" },
  { u: "omar", p: "1234", name: "Omar", role: "salesman" },
  { u: "rami", p: "1234", name: "Rami", role: "salesman" },
  { u: "sabri", p: "1234", name: "Sabri", role: "salesman" },
  { u: "sameh", p: "1234", name: "Sameh", role: "salesman" },
  { u: "sami", p: "1234", name: "Sami", role: "salesman" },
  { u: "tarek", p: "1234", name: "Tarek", role: "salesman" },
  { u: "wael", p: "1234", name: "Wael", role: "salesman" },
  { u: "waleed", p: "1234", name: "Waleed", role: "salesman" },
  { u: "yousef", p: "1234", name: "Yousef", role: "salesman" },
  { u: "ziad", p: "1234", name: "Ziad", role: "salesman" },
];

module.exports = { SEED, DEFAULT_DIST, DEFAULT_USERS };
